version: '3'
services:
  app:
    build: .
    container_name: nest-app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - mongo
    command: npm run start:dev

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    container_name: redis-dev
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
